#!/bin/bash

VIMDIR="$HOME/.vim/bundle"

[ -f "$HOME/.vimrc" ] && \
    [ -d "$VIMDIR/Vundle.vim" ] && \
    [ -d "$VIMDIR/YouCompleteMe" ] && \
    [ -d "$VIMDIR/ale" ] && \
    [ -d "$VIMDIR/asyncrun.vim" ] && \
    [ -d "$VIMDIR/ctrlp.vim" ] && \
    [ -d "$VIMDIR/emmet-vim" ] && \
    [ -d "$VIMDIR/vim-autoclose" ] && \
    [ -d "$VIMDIR/vim-closetag" ] && \
    [ -d "$VIMDIR/vim-javascript" ] && \
    [ -d "$VIMDIR/vim-jsx" ]
